### ISSUE TITLE
ATEMSYS_IOCTL_PCI_CONF_DEVICE failed: -14

### ISSUE THREAD

**Issue by ishibashi-kyosuke** [acontis/atemsys#1]
@ec-support 

I faced with the following error when I try to use atemsys.
`ATEMSYS_IOCTL_PCI_CONF_DEVICE failed: -14`
I'm using rt kernel on ubuntu20.04 which is  5.4.143-rt64.
PCI device using on my PC is Intel Corporation 82579V Gigabit Network Connection whose vendor id is 0x8086 and device id 0x1503.
I'm glad to have some information of this error and how to solve this problem.

**Comment by ec-support** [comment]
Can you provide us the kernel log messages?
``dmesg | grep atemsys``

**Comment by ishibashi-kyosuke** [comment]
This is output of the command.
Error occurs in line 153 and 299.
[output.txt](https://github.com/acontis/atemsys/files/11730072/output.txt)

**Comment by ec-support** [comment]
It looks like the IOCTL is being called with wrong parameters. I assume the problems are related to the EC-Master, so I would ask you to forward the issue to ecsupport@acontis.com. The EC-Master team will then take care of it.
