### ISSUE TITLE
Build fails with kernel 6.5

### ISSUE THREAD

**Issue by eibach** [acontis/atemsys#2]
/home/eibachd/src/atemsys/atemsys.c: In function ‘device_mmap’:
/home/eibachd/src/atemsys/atemsys.c:1935:18: error: assignment of read-only member ‘vm_flags’
 1935 |    vma->vm_flags |= VM_RESERVED | VM_LOCKED | VM_DONTCOPY;
      |                  ^~
/home/eibachd/src/atemsys/atemsys.c:1992:21: error: assignment of read-only member ‘vm_flags’
 1992 |       vma->vm_flags |= VM_IO;
      |                     ^~
/home/eibachd/src/atemsys/atemsys.c: In function ‘ResetPhyViaGpio’:
/home/eibachd/src/atemsys/atemsys.c:3304:5: error: implicit declaration of function ‘devm_gpio_free’; did you mean ‘devm_gpiod_get’? [-Werror=implicit-function-declaration]
 3304 |     devm_gpio_free(&pDrvDescPrivate->pPDev->dev, pDrvDescPrivate->nPhyResetGpioPin);
      |     ^~~~~~~~~~~~~~
      |     devm_gpiod_get
In file included from /usr/src/linux-headers-6.5.0-2-reform2-common/arch/arm64/include/asm/lse.h:12,
                 from /usr/src/linux-heaazders-6.5.0-2-reform2-common/arch/arm64/include/asm/cmpxchg.h:14,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/arch/arm64/include/asm/atomic.h:16,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/atomic.h:7,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/asm-generic/bitops/atomic.h:5,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/arch/arm64/include/asm/bitops.h:25,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/bitops.h:68,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/arch/arm64/include/asm/cache.h:40,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/cache.h:6,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/time.h:5,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/arch/arm64/include/asm/stat.h:12,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/stat.h:6,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/module.h:13,
                 from /home/eibachd/src/atemsys/atemsys.c:98:
/home/eibachd/src/atemsys/atemsys.c: In function ‘init_module’:
/usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/export.h:29:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   29 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
/home/eibachd/src/atemsys/atemsys.c:4064:32: note: in expansion of macro ‘THIS_MODULE’
 4064 |     S_pDevClass = class_create(THIS_MODULE, ATEMSYS_DEVICE_NAME);
      |                                ^~~~~~~~~~~
In file included from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/device.h:31,
                 from /usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/pci.h:37,
                 from /home/eibachd/src/atemsys/atemsys.c:100:
/usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  230 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/home/eibachd/src/atemsys/atemsys.c:4064:19: error: too many arguments to function ‘class_create’
 4064 |     S_pDevClass = class_create(THIS_MODULE, ATEMSYS_DEVICE_NAME);
      |                   ^~~~~~~~~~~~
/usr/src/linux-headers-6.5.0-2-reform2-common/include/linux/device/class.h:230:29: note: declared here
  230 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.5.0-2-reform2-common/scripts/Makefile.build:248: /home/eibachd/src/atemsys/atemsys.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.5.0-2-reform2-common/Makefile:2059: /home/eibachd/src/atemsys] Error 2
make[1]: *** [/usr/src/linux-headers-6.5.0-2-reform2-common/Makefile:246: __sub-make] Error 2
make: *** [Makefile:28: modules] Error 2

**Comment by ec-support** [comment]
Fixed with Release v1.4.28
