### ISSUE TITLE
Build error on Ubuntu 24.04 raspi

### ISSUE THREAD

**Issue by jtech-oka** [acontis/atemsys#5]
I'm trying to build atemsys v1.4.30 on Raspberry Pi 4B with Ubuntu 24.04/6.8.0-1010-raspi.
I installed build-essential and linux-headers-6.8.0-1010-raspi/linux-raspi-headers-6.8.0-1010.
Then I try to build but errors shown below happen.
It has no errors on RaspiOS/6.6.31+rpt-rpi-v8 and Ubuntu 24.04/6.8.0-41-lowlatency amd64.
So, I think any kernel config which atemsys required is missing on  6.8.0-1010-raspi, but I cannot find out which one is it.
Please give me any advice.
Thnaks.
----------
$ make CC=aarch64-linux-gnu-gcc-13 modules
make -C /lib/modules/6.8.0-1010-raspi/build M=/home/ubuntu/work/atemsys-1.4.30 modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-1010-raspi'
  CC [M]  /home/ubuntu/work/atemsys-1.4.30/atemsys.o
/home/ubuntu/work/atemsys-1.4.30/atemsys.c: In function ‘MdioProbe’:
/home/ubuntu/work/atemsys-1.4.30/atemsys.c:3641:16: error: implicit declaration of function ‘of_find_device_by_node’; did you mean ‘of_find_net_device_by_node’? [-Werror=implicit-function-declaration]
 3641 |         mdio = of_find_device_by_node(pDrvDescPrivate->pMdioNode);
      |                ^~~~~~~~~~~~~~~~~~~~~~
      |                of_find_net_device_by_node
/home/ubuntu/work/atemsys-1.4.30/atemsys.c:3641:14: warning: assignment to ‘struct platform_device *’ from ‘in ’ makes pointer from integer without a cast [-Wint-conversion]
 3641 |         mdio = of_find_device_by_node(pDrvDescPrivate->pMdioNode);
      |              ^
/home/ubuntu/work/atemsys-1.4.30/atemsys.c:3659:13: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
 3659 |             strlcpy(mdio_bus_id, pDrvDescPrivate->pMdioBus->id, MII_BUS_ID_SIZE);
      |             ^~~~~~~
      |             strscpy
/home/ubuntu/work/atemsys-1.4.30/atemsys.c: In function ‘EthernetDriverProbe’:
/home/ubuntu/work/atemsys-1.4.30/atemsys.c:4388:9: error: implicit declaration of function ‘of_platform_populate ’ [-Werror=implicit-function-declaration]
 4388 |         of_platform_populate(pDevNode, NULL, NULL, &pPDev->dev);
      |         ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/ubuntu/work/atemsys-1.4.30/atemsys.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-1010-raspi/Makefile:1926: /home/ubuntu/work/atemsys-1.4.30] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-1010-raspi'
make: *** [Makefile:28: modules] Error 2

**Comment by ec-support** [comment]
Fixed with Release v1.4.32
